twig:
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true

    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/assets/css': style