controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # app_ajouter:
    #     path: "/ajouter/{id}"
    #     controller: "App\Service\PanierService::add"
